# .circleci/config.yml

version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout

      - run:
          name: Restore Dependencies
          command: dotnet restore

      - run:
          name: Build Application
          command: dotnet build

      - run:
          name: Run Tests
          command: dotnet test
